services:
  calibre-web:
    image: linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
    volumes:
      - ./calibre-library:/books
      - ./config:/config
    ports:
      - "8083:8083"
    restart: unless-stopped
